name: Build Frontend
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build, test and deploy frontend
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend
      - run: cd frontend && yarn build